version: 2
updates:
  # Python dependencies.
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"

  # GitHub Actions dependencies.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
