repos:
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell

- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.8.1
  hooks:
  - id: markdownlint-cli2

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
      language_version: python3.11

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
    - id: pydocstyle
      args: [
        "--convention=google"
      ]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)

- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args: [
        "--rcfile=pylintrc"
      ]
