name: Checks
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  pre_commit:
    name: Pre-Commit
    uses: ./.github/workflows/pre_commit.yml

  pytest:
      name: Pytest
      uses: ./.github/workflows/pytest.yml
